apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-python-server
  name: grpc-python-server-deployment
  namespace: grpc-python
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50051
    nodePort: 31769
    targetPort: 50051
    protocol: TCP
  selector:
    app: grpc-python-server
  sessionAffinity: None
  type: NodePort
