apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: grpc-python-server
  name: grpc-python-server-deployment
  namespace: grpc-python
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grpc-python-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grpc-python-server
    spec:
      containers:
      - image: ghcr.io/semashkinvg/python-server-data-transfer:latest
        imagePullPolicy: Always
        name: grpc-python-server
        ports:
        - containerPort: 50051
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
