apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-python-server
  name: grpc-python-server-deployment
  namespace: grpc-python
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31769
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: grpc-python-server
  sessionAffinity: None
  type: LoadBalancer
