kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ .Values.docker.config.secret_name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: docker-github-container-registry-secret
data:
  .dockerconfigjson: {{ .Values.docker.config.ghcr_content }}
