apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: grpc-python-server-deployment
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50051
    nodePort: 31769
    targetPort: 50051
    protocol: TCP
  selector:
    app: {{ .Values.app }}
  sessionAffinity: None
  type: NodePort
